export const COLORS = {
  background: "#F8FAFC",
  surface: "#FFFFFF",
  textPrimary: "#0F172A",
  textSecondary: "#64748B",
  border: "#CBD5E1",
  primary: "#2563EB",
  white: "#FFFFFF",
  onboardingPrimary: "#003C52",
  onboardingTint: "#ECFEFF",
  onboardingAccent: "#06B6D4",
  onboardingDot: "#CBD5E1",
  authBg: "#F2F2F4",
  authInput: "#F7F7F8",
  authBorder: "#E5E7EB",
  authMuted: "#E5E7EB",
  authPlaceholder: "#A3A7AF",
  authAccent: "#F59E0B",
} as const;
